query FetchPage($url: String!) {
    all_global_settings {
        ...GlobalSettingsFields
    }
    all_page(where: { url: $url }) {
        total
        items {
            title
            url
            global_field {
                canonical {
                    href
                    title
                }
                description
                nofollow
                noindex
                og_tags {
                    key
                    value
                }
                schema
                title
            }
            main_content {
                ... on PageMainContentMainCopy {
                    __typename
                    main_copy {
                        item {
                            json
                        }
                        title
                    }
                }
            }
            featured_contentConnection {
                edges {
                    node {
                        ... on Dog {
                            ...DogFields
                        }
                    }
                }
            }
            system {
                created_at
                uid
            }
        }
    }
}
