fragment GlobalSettingsFields on AllGlobalSettings {
    items {
        attribution
        copyright
        default_dog_imageConnection {
            edges {
                node {
                    url
                    dimension {
                        height
                        width
                    }
                    system {
                        created_at
                        uid
                    }
                }
            }
        }
        faviconConnection {
            edges {
                node {
                    url
                    dimension {
                        height
                        width
                    }
                    system {
                        created_at
                        uid
                    }
                }
            }
        }
        site_title
        logoConnection {
            edges {
                node {
                    url
                    dimension {
                        height
                        width
                    }
                    system {
                        created_at
                        uid
                    }
                }
            }
        }
    }
}
